[project]
name = "zoo-service-template"
version = "0.1.0"
description = "Zoo service template"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "boto3>=1.38.32",
    "cwltool>=3.1.20250110105449",
    "urllib3==2.6.3",
    "ruff",
    "pydocstyle"
]

[dependency-groups]
dev = [
    "cwl-utils>=0.40",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[pytest]
[tool.pytest.ini_options]
testpaths=["tests"]

[tool.ruff]
include = ["pyproject.toml", "tests/*.py", "**/__init__.py", "**/cwl_helper.py"]
line-length = 180
force-exclude = true
extend-exclude = ["{{cookiecutter.service_name}}/service.py"]

[tool.ruff.lint]
select = ["E", "F"]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"tests/test_finalize_cwl.py" = ["E402"]

[tool.towncrier]
package = "src"
directory = "newsfragments"
filename = "CHANGELOG.md"

[tool.towncrier.fragment.feature]
[tool.towncrier.fragment.fix]
[tool.towncrier.fragment.removal]

[tool.towncrier.fragment.misc]
name = "Misc"
showcontent = true

[tool.towncrier.fragment.doc]

[tool.pydocstyle]
match_dir = "^(?!(.venv|tests|e2e|migration)).*"
